version: "3.9"
services:
    app:
        container_name: case_study
        build: .
        ports:
            - "65431:65431"
        links:
            - db
        depends_on:
            - db
    db:
        image: "postgres"
        environment:
            POSTGRES_PASSWORD: mypostgres
            POSTGRES_USER: postgres
            POSTGRES_DB: case_study
